import { defineConfig } from "oxlint";

export default defineConfig({
  $schema: "./node_modules/oxlint/configuration_schema.json",
  plugins: ["typescript", "react", "import", "oxc", "unicorn", "promise", "vitest", "jsx-a11y"],
  env: { browser: true, es2022: true },
  settings: {
    react: { version: "19.0" },
  },
  ignorePatterns: [
    "dist",
    "coverage",
    "node_modules",
    "draft",
    "bun.lock",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
  ],
  options: {
    denyWarnings: true,
  },
  categories: {
    correctness: "error",
    suspicious: "error",
  },
  rules: {
    "react/react-in-jsx-scope": "off",
    "typescript/no-explicit-any": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/no-import-type-side-effects": "error",
    "import/no-mutable-exports": "error",
    "import/no-unassigned-import": "off",
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "import/no-anonymous-default-export": "error",
    "import/no-amd": "error",
    "import/no-default-export": "off",
    "import/prefer-default-export": "off",
    "import/no-named-export": "off",
    "import/exports-last": "off",
    "react/jsx-key": "error",
    "react/self-closing-comp": "error",
    "react/jsx-boolean-value": ["error", "never"],
    "react/jsx-no-useless-fragment": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-pascal-case": "error",
    "react/jsx-no-undef": "error",
    "react/jsx-no-constructed-context-values": "error",
    "react/no-children-prop": "error",
    "react/no-danger": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-unescaped-entities": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/throw-new-error": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/no-unnecessary-await": "error",
    "promise/no-return-wrap": "error",
    "promise/no-promise-in-callback": "error",
    "promise/no-nesting": "error",
    "promise/valid-params": "error",
    "promise/catch-or-return": "error",
    "promise/no-new-statics": "error",
    "eslint/no-console": ["error", { allow: ["warn", "error"] }],
    "eslint/eqeqeq": ["error", "always", { null: "ignore" }],
    "eslint/no-constant-binary-expression": "error",
    "eslint/no-constant-condition": "error",
    "eslint/no-unreachable": "error",
    "eslint/no-fallthrough": "error",
    "eslint/no-self-assign": "error",
    "eslint/no-duplicate-imports": "off",
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/anchor-has-content": "error",
    "jsx-a11y/anchor-is-valid": "error",
    "jsx-a11y/heading-has-content": "error",
    "jsx-a11y/iframe-has-title": "error",
    "jsx-a11y/no-distracting-elements": "error",
    "jsx-a11y/no-redundant-roles": "error",
    "jsx-a11y/role-has-required-aria-props": "error",
    "jsx-a11y/role-supports-aria-props": "error",
    "vitest/no-import-node-test": "error",
    "vitest/prefer-to-be": "error",
    "vitest/require-to-throw-message": "error",
  },
  overrides: [
    {
      files: [
        "vite.config.ts",
        "vitest.config.ts",
        "oxlint.config.ts",
        "oxfmt.config.ts",
        "commitlint.config.mjs",
      ],
      env: { node: true, browser: false },
      rules: {
        "import/no-unassigned-import": "off",
        "eslint/no-console": "off",
        "jsx-a11y/anchor-is-valid": "off",
        "import/no-default-export": "off",
        "import/prefer-default-export": "off",
        "import/no-anonymous-default-export": "off",
      },
    },
    {
      files: ["scripts/**/*"],
      env: { node: true, browser: false },
      rules: {
        "eslint/no-console": "off",
        "eslint/eqeqeq": "off",
      },
    },
    {
      files: ["src/test/**/*", "**/*.test.ts", "**/*.test.tsx", "**/*.spec.ts", "**/*.spec.tsx"],
      env: { browser: true },
      rules: {
        "import/no-default-export": "off",
        "import/prefer-default-export": "off",
        "import/no-anonymous-default-export": "off",
        "jsx-a11y/click-events-have-key-events": "off",
        "jsx-a11y/no-autofocus": "off",
        "eslint/no-console": "off",
        "promise/catch-or-return": "off",
        "promise/no-nesting": "off",
        "import/no-unassigned-import": "off",
      },
    },
  ],
});
